- name: bind packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - bind9
    - bind9-host
    - cron
  tags: bind

- name: zone directory
  file:
    path: /etc/bind/zones
    owner: bind
    group: bind
    mode: 0700
    state: directory
  tags: bind

- name: log directory
  file:
    path: /var/log/named
    owner: bind
    group: bind
    mode: 0700
    state: directory
  tags: bind

- name: config files
  template:
    src: '{{ item }}.j2'
    dest: '/etc/bind/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - named.conf
    - named.conf.options
    - named.conf.local
  notify: bind config changed
  tags: bind

- name: keys directory
  file:
    path: /etc/bind/keys
    owner: root
    group: bind
    mode: 0750
    state: directory
  tags: bind

- include: keys.yml
  when: bind_role == 'master'

- include: zone.yml
  when: bind_role == 'master'

- name: bind enabled and started
  service:
    name: bind9
    enabled: yes
    state: started
  tags: bind
